# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Default
  

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
- task: CmdLine@2
  inputs:
    script: |
      cd /opt/myagent/_work/2/s/target
      cp org.jacoco.examples.maven.java-1.0-SNAPSHOT.jar /var/lib/tomcat9/webapps/
      java -jar /var/lib/tomcat9/webapps/org.jacoco.examples.maven.java-1.0-SNAPSHOT.jar
